"""Phase 5 sales tools: notes, objections, follow-ups, calendar, handoffs, tool audit.

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-09 10:55:48.054910
"""

import re
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_ROLE_PATTERN = re.compile(r"^[a-z_][a-z0-9_]{0,62}$")
_TENANT_TABLES = (
    "lead_notes",
    "objections",
    "followups",
    "scheduling_settings",
    "appointments",
    "handoffs",
    "tool_executions",
)


def _app_role() -> str:
    role = op.get_context().config.attributes["app_role"]  # type: ignore[union-attr]
    if not isinstance(role, str) or not _ROLE_PATTERN.fullmatch(role):
        raise ValueError("invalid application role name")
    return role


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduling_settings",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("work_days", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column("day_start_minute", sa.Integer(), nullable=False),
        sa.Column("day_end_minute", sa.Integer(), nullable=False),
        sa.Column("slot_minutes", sa.Integer(), nullable=False),
        sa.Column("min_notice_minutes", sa.Integer(), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_scheduling_settings_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_scheduling_settings")),
    )
    op.create_table(
        "appointments",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("call_id", sa.Uuid(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('booked', 'cancelled')", name=op.f("ck_appointments_status")
        ),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_appointments_ends_after_start")),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["calls.id"],
            name=op.f("fk_appointments_call_id_calls"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_appointments_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_appointments_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointments")),
    )
    op.create_index(op.f("ix_appointments_lead_id"), "appointments", ["lead_id"], unique=False)
    op.create_index(op.f("ix_appointments_tenant_id"), "appointments", ["tenant_id"], unique=False)
    op.create_index(
        "uq_appointments_booked_slot",
        "appointments",
        ["tenant_id", "starts_at"],
        unique=True,
        postgresql_where=sa.text("status = 'booked'"),
    )
    op.create_table(
        "followups",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("call_id", sa.Uuid(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "channel IN ('call', 'email', 'whatsapp')", name=op.f("ck_followups_channel")
        ),
        sa.CheckConstraint(
            "status IN ('scheduled', 'done', 'cancelled')", name=op.f("ck_followups_status")
        ),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("fk_followups_call_id_calls"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_followups_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_followups_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_followups")),
    )
    op.create_index(op.f("ix_followups_lead_id"), "followups", ["lead_id"], unique=False)
    op.create_index(op.f("ix_followups_tenant_id"), "followups", ["tenant_id"], unique=False)
    op.create_table(
        "handoffs",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("call_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("urgency", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('open', 'resolved')", name=op.f("ck_handoffs_status")),
        sa.CheckConstraint(
            "urgency IN ('low', 'normal', 'high')", name=op.f("ck_handoffs_urgency")
        ),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("fk_handoffs_call_id_calls"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_handoffs_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_handoffs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_handoffs")),
    )
    op.create_index(op.f("ix_handoffs_lead_id"), "handoffs", ["lead_id"], unique=False)
    op.create_index(op.f("ix_handoffs_tenant_id"), "handoffs", ["tenant_id"], unique=False)
    op.create_table(
        "lead_notes",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("call_id", sa.Uuid(), nullable=True),
        sa.Column("text", sa.String(length=1000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("fk_lead_notes_call_id_calls"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_lead_notes_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_lead_notes_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_notes")),
    )
    op.create_index(op.f("ix_lead_notes_lead_id"), "lead_notes", ["lead_id"], unique=False)
    op.create_index(op.f("ix_lead_notes_tenant_id"), "lead_notes", ["tenant_id"], unique=False)
    op.create_table(
        "objections",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("call_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("detail", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "category IN ('price', 'timing', 'competitor', 'trust', 'no_need', 'authority',"
            " 'other')",
            name=op.f("ck_objections_category"),
        ),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("fk_objections_call_id_calls"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_objections_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_objections_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_objections")),
    )
    op.create_index(op.f("ix_objections_lead_id"), "objections", ["lead_id"], unique=False)
    op.create_index(op.f("ix_objections_tenant_id"), "objections", ["tenant_id"], unique=False)
    op.create_table(
        "tool_executions",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("call_id", sa.Uuid(), nullable=True),
        sa.Column("tool", sa.String(length=50), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.String(length=50), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('ok', 'rejected', 'failed')", name=op.f("ck_tool_executions_status")
        ),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["calls.id"],
            name=op.f("fk_tool_executions_call_id_calls"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tool_executions_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_executions")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_tool_executions_idempotency_key")),
    )
    op.create_index(
        op.f("ix_tool_executions_call_id"), "tool_executions", ["call_id"], unique=False
    )
    op.create_index(
        op.f("ix_tool_executions_tenant_id"), "tool_executions", ["tenant_id"], unique=False
    )
    op.add_column(
        "leads",
        sa.Column("interest", sa.String(length=20), nullable=False, server_default="unknown"),
    )
    op.add_column("leads", sa.Column("interest_reason", sa.String(length=500), nullable=True))
    op.add_column(
        "leads",
        sa.Column(
            "qualification",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.create_check_constraint(
        op.f("ck_leads_interest"),
        "leads",
        "interest IN ('unknown', 'interested', 'not_interested')",
    )

    # --- Tenant isolation and application-role privileges -----------------------------
    for table in _TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (tenant_id = app_current_tenant()) "
            "WITH CHECK (tenant_id = app_current_tenant())"
        )
    role = _app_role()  # validated identifier: safe to interpolate
    # Records of what happened are append-only; scheduled items change status, never vanish.
    op.execute(f"GRANT SELECT, INSERT ON lead_notes, objections, tool_executions TO {role}")
    op.execute(
        f"GRANT SELECT, INSERT, UPDATE ON followups, appointments, handoffs, "
        f"scheduling_settings TO {role}"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_leads_interest"), "leads", type_="check")
    op.drop_column("leads", "qualification")
    op.drop_column("leads", "interest_reason")
    op.drop_column("leads", "interest")
    op.drop_index(op.f("ix_tool_executions_tenant_id"), table_name="tool_executions")
    op.drop_index(op.f("ix_tool_executions_call_id"), table_name="tool_executions")
    op.drop_table("tool_executions")
    op.drop_index(op.f("ix_objections_tenant_id"), table_name="objections")
    op.drop_index(op.f("ix_objections_lead_id"), table_name="objections")
    op.drop_table("objections")
    op.drop_index(op.f("ix_lead_notes_tenant_id"), table_name="lead_notes")
    op.drop_index(op.f("ix_lead_notes_lead_id"), table_name="lead_notes")
    op.drop_table("lead_notes")
    op.drop_index(op.f("ix_handoffs_tenant_id"), table_name="handoffs")
    op.drop_index(op.f("ix_handoffs_lead_id"), table_name="handoffs")
    op.drop_table("handoffs")
    op.drop_index(op.f("ix_followups_tenant_id"), table_name="followups")
    op.drop_index(op.f("ix_followups_lead_id"), table_name="followups")
    op.drop_table("followups")
    op.drop_index(
        "uq_appointments_booked_slot",
        table_name="appointments",
        postgresql_where=sa.text("status = 'booked'"),
    )
    op.drop_index(op.f("ix_appointments_tenant_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_lead_id"), table_name="appointments")
    op.drop_table("appointments")
    op.drop_table("scheduling_settings")
    # ### end Alembic commands ###
