"""Voice worker entrypoint.

Run: ``python -m aurevia_voice.main start`` (or ``dev`` for auto-reload).

The backend creates a LiveKit room per call and dispatches this agent into it with the call's
id and per-call token as job metadata. The worker then: starts the call with the backend,
speaks the agent's greeting, and lets LiveKit run listening, turn detection and interruption
while every reply comes from the backend. On the way out it reports STT/TTS usage and ends
the call.
"""

from __future__ import annotations

import asyncio
import json
import logging
import sys
from typing import Any

from livekit.agents import (
    Agent,
    AgentServer,
    AgentSession,
    JobContext,
    JobProcess,
    TurnHandlingOptions,
    cli,
)
from livekit.agents.metrics.usage import STTModelUsage, TTSModelUsage

from aurevia_voice.backend_client import BackendClient, BackendError
from aurevia_voice.config import WorkerSettings
from aurevia_voice.llm_bridge import BackendLLM
from aurevia_voice.redaction import install_log_redaction
from aurevia_voice.silence import SilenceTracker
from aurevia_voice.speech_providers import (
    SpeechOptions,
    build_stt,
    build_tts,
    load_vad,
    missing_keys,
)
from aurevia_voice.turn_metrics import TurnMetricsCollector

logger = logging.getLogger("aurevia.voice")

settings = WorkerSettings()  # type: ignore[call-arg]  # backend_url comes from the environment


def prewarm(proc: JobProcess) -> None:
    # Loading the voice activity model once per process keeps call start fast.
    install_log_redaction()  # job processes log too
    proc.userdata["vad"] = load_vad()


server = AgentServer(setup_fnc=prewarm)


async def _finish(
    session: AgentSession[Any],
    backend: BackendClient,
    collector: TurnMetricsCollector,
    reason: str,
) -> None:
    try:
        if collector.turns:
            await backend.report_turn_metrics(collector.turns)
        for usage in session.usage.model_usage:
            if isinstance(usage, STTModelUsage):
                await backend.report_usage(
                    kind="stt",
                    provider=usage.provider,
                    model=usage.model,
                    audio_seconds=usage.audio_duration,
                )
            elif isinstance(usage, TTSModelUsage):
                await backend.report_usage(
                    kind="tts",
                    provider=usage.provider,
                    model=usage.model,
                    characters=usage.characters_count,
                )
        await backend.end(_reason_code(reason))
    except BackendError:
        logger.exception("Could not close the call with the backend")
    finally:
        await backend.aclose()


def turn_handling(config: WorkerSettings) -> TurnHandlingOptions:
    return {
        "endpointing": {
            "mode": config.endpointing_mode,
            "min_delay": config.endpointing_min_delay,
            "max_delay": config.endpointing_max_delay,
        },
        "preemptive_generation": {"enabled": config.preemptive_generation},
        "interruption": {"min_duration": config.interruption_min_duration},
    }


def _reason_code(reason: str) -> str:
    code = "".join(c if c.isalnum() else "_" for c in reason.lower()).strip("_")
    return code[:100] or "unknown"


@server.rtc_session(agent_name=settings.agent_name)
async def entrypoint(ctx: JobContext) -> None:
    metadata = json.loads(ctx.job.metadata or "{}")
    backend = BackendClient(
        base_url=settings.backend_url,
        call_id=metadata["call_id"],
        call_token=metadata["call_token"],
    )
    opening = await backend.start()
    logger.info("Call started", extra={"call_id": metadata["call_id"]})

    try:
        speech = SpeechOptions(
            stt_provider=settings.stt_provider,
            tts_provider=settings.tts_provider,
            stt_model=settings.stt_model,
            stt_language=settings.stt_language,
            tts_model=settings.tts_model,
            tts_voice=opening.voice or settings.tts_voice,
            tts_language=opening.language.split("-")[0],
        )
        session: AgentSession[Any] = AgentSession(
            stt=build_stt(speech),
            tts=build_tts(speech),
            vad=ctx.proc.userdata["vad"],
            llm=BackendLLM(backend),
            turn_handling=turn_handling(settings),
            user_away_timeout=settings.silence_timeout_seconds,
        )
        await ctx.connect()
        # The instructions are a placeholder: the backend builds the real prompt every turn.
        await session.start(
            agent=Agent(instructions="Replies are generated by the Aurevia backend."),
            room=ctx.room,
        )
    except Exception:
        # The call was started with the backend; never leave it looking in progress.
        logger.exception("Voice session setup failed", extra={"call_id": metadata["call_id"]})
        try:
            await backend.end("worker_error", failed=True)
        finally:
            await backend.aclose()
        raise

    silence = SilenceTracker(reprompts_before_hang_up=settings.silence_reprompts)

    async def end_after_goodbye() -> None:
        handle = session.say(settings.silence_goodbye_text, allow_interruptions=False)
        await handle.wait_for_playout()
        ctx.shutdown(reason="prospect_silent")

    def on_user_state(event: Any) -> None:
        action = silence.on_user_state(event.new_state)
        if action == "reprompt":
            session.say(settings.silence_reprompt_text)
        elif action == "hang_up":
            tasks.add(task := asyncio.create_task(end_after_goodbye()))
            task.add_done_callback(tasks.discard)

    tasks: set[asyncio.Task[None]] = set()
    session.on("user_state_changed", on_user_state)

    collector = TurnMetricsCollector()
    session.on("conversation_item_added", lambda event: collector.add(event.item))

    async def on_shutdown(reason: str) -> None:
        await _finish(session, backend, collector, reason)

    ctx.add_shutdown_callback(on_shutdown)
    session.on("close", lambda event: ctx.shutdown(reason=str(event.reason)))
    session.say(opening.greeting)


def main() -> None:
    install_log_redaction()
    serving = len(sys.argv) > 1 and sys.argv[1] in ("start", "dev", "connect")
    missing = missing_keys(settings.stt_provider, settings.tts_provider)
    if serving and missing:
        # A worker that cannot speak or listen must not accept calls.
        sys.exit(f"Refusing to start: set {', '.join(missing)}")
    cli.run_app(server)


if __name__ == "__main__":
    main()
