"""Voice worker entrypoint.

Run: ``python -m aurevia_voice.main start`` (or ``dev`` for auto-reload).

The backend creates a LiveKit room per call and dispatches this agent into it with the call's
id and per-call token as job metadata. The worker then: starts the call with the backend,
speaks the agent's greeting, and lets LiveKit run listening, turn detection and interruption
while every reply comes from the backend. On the way out it reports STT/TTS usage and ends
the call.
"""

from __future__ import annotations

import json
import logging
import os
import sys
from typing import Any

from livekit.agents import Agent, AgentServer, AgentSession, JobContext, JobProcess, cli
from livekit.agents.metrics.usage import STTModelUsage, TTSModelUsage
from livekit.plugins import cartesia, deepgram, silero

from aurevia_voice.backend_client import BackendClient, BackendError
from aurevia_voice.config import WorkerSettings
from aurevia_voice.llm_bridge import BackendLLM

logger = logging.getLogger("aurevia.voice")

settings = WorkerSettings()  # type: ignore[call-arg]  # backend_url comes from the environment


def prewarm(proc: JobProcess) -> None:
    # Loading the voice activity model once per process keeps call start fast.
    proc.userdata["vad"] = silero.VAD.load()


server = AgentServer(setup_fnc=prewarm)


async def _finish(session: AgentSession[Any], backend: BackendClient, reason: str) -> None:
    try:
        for usage in session.usage.model_usage:
            if isinstance(usage, STTModelUsage):
                await backend.report_usage(
                    kind="stt",
                    provider=usage.provider,
                    model=usage.model,
                    audio_seconds=usage.audio_duration,
                )
            elif isinstance(usage, TTSModelUsage):
                await backend.report_usage(
                    kind="tts",
                    provider=usage.provider,
                    model=usage.model,
                    characters=usage.characters_count,
                )
        await backend.end(_reason_code(reason))
    except BackendError:
        logger.exception("Could not close the call with the backend")
    finally:
        await backend.aclose()


def _reason_code(reason: str) -> str:
    code = "".join(c if c.isalnum() else "_" for c in reason.lower()).strip("_")
    return code[:100] or "unknown"


@server.rtc_session(agent_name=settings.agent_name)
async def entrypoint(ctx: JobContext) -> None:
    metadata = json.loads(ctx.job.metadata or "{}")
    backend = BackendClient(
        base_url=settings.backend_url,
        call_id=metadata["call_id"],
        call_token=metadata["call_token"],
    )
    opening = await backend.start()
    logger.info("Call started", extra={"call_id": metadata["call_id"]})

    try:
        tts_options: dict[str, Any] = {"language": opening.language.split("-")[0]}
        if settings.tts_model:
            tts_options["model"] = settings.tts_model
        if opening.voice or settings.tts_voice:
            tts_options["voice"] = opening.voice or settings.tts_voice

        session: AgentSession[Any] = AgentSession(
            stt=deepgram.STT(model=settings.stt_model, language=settings.stt_language),
            tts=cartesia.TTS(**tts_options),
            vad=ctx.proc.userdata["vad"],
            llm=BackendLLM(backend),
        )
        await ctx.connect()
        # The instructions are a placeholder: the backend builds the real prompt every turn.
        await session.start(
            agent=Agent(instructions="Replies are generated by the Aurevia backend."),
            room=ctx.room,
        )
    except Exception:
        # The call was started with the backend; never leave it looking in progress.
        logger.exception("Voice session setup failed", extra={"call_id": metadata["call_id"]})
        try:
            await backend.end("worker_error", failed=True)
        finally:
            await backend.aclose()
        raise

    async def on_shutdown(reason: str) -> None:
        await _finish(session, backend, reason)

    ctx.add_shutdown_callback(on_shutdown)
    session.on("close", lambda event: ctx.shutdown(reason=str(event.reason)))
    session.say(opening.greeting)


REQUIRED_VENDOR_KEYS = ("DEEPGRAM_API_KEY", "CARTESIA_API_KEY")


def main() -> None:
    serving = len(sys.argv) > 1 and sys.argv[1] in ("start", "dev", "connect")
    missing = [key for key in REQUIRED_VENDOR_KEYS if not os.environ.get(key)]
    if serving and missing:
        # A worker that cannot speak or listen must not accept calls.
        sys.exit(f"Refusing to start: set {', '.join(missing)}")
    cli.run_app(server)


if __name__ == "__main__":
    main()
